@Yape.TransactionService.API_HostAddress = https://localhost:7241

POST {{Yape.TransactionService.API_HostAddress}}/api/Transactions
Accept: application/json
Content-Type: application/json
{
  "amount": 5900.689
}
